# Generated by Django 3.2.25 on 2026-03-06 20:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=100, verbose_name='Шифр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'work_project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('task', 'План задач (ПО)'), ('pp', 'Производственный план (ПП)')], max_length=10, verbose_name='Источник')),
                ('work_name', models.CharField(max_length=500, verbose_name='Наименование работы')),
                ('work_number', models.CharField(blank=True, max_length=100, verbose_name='Номер работы / документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание / обоснование')),
                ('executor_name_raw', models.CharField(blank=True, max_length=200, verbose_name='Исполнитель (текст)')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Начало работы')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Конец работы')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Контрольный срок')),
                ('plan_hours', models.JSONField(blank=True, default=dict, verbose_name='Плановые часы (по месяцам)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_works', to='employees.employee', verbose_name='Создал')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='employees.department', verbose_name='Отдел')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='employees.employee', verbose_name='Исполнитель')),
                ('ntc_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='employees.ntccenter', verbose_name='НТЦ-центр')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.project', verbose_name='Проект')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='employees.sector', verbose_name='Сектор')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'work_work',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
                'db_table': 'work_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(blank=True, max_length=500, verbose_name='Наименование документа')),
                ('doc_designation', models.CharField(blank=True, max_length=200, verbose_name='Обозначение')),
                ('inventory_num', models.CharField(blank=True, max_length=100, verbose_name='Инв. номер')),
                ('date_accepted', models.DateField(blank=True, null=True, verbose_name='Дата сдачи')),
                ('doc_type', models.CharField(blank=True, choices=[('design', 'Конструкторский'), ('tech', 'Технологический'), ('report', 'Отчёт'), ('program', 'Программа испытаний'), ('other', 'Прочее')], max_length=20, verbose_name='Вид документа')),
                ('doc_class', models.CharField(blank=True, choices=[('original', 'Подлинник'), ('copy', 'Копия'), ('draft', 'Черновик')], max_length=20, verbose_name='Класс документа')),
                ('sheets_a4', models.PositiveIntegerField(blank=True, null=True, verbose_name='Листов А4')),
                ('norm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Норма')),
                ('coeff', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Коэффициент')),
                ('bvd_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Часы БВД')),
                ('norm_control', models.CharField(blank=True, max_length=200, verbose_name='Нормоконтролёр')),
                ('doc_link', models.URLField(blank=True, verbose_name='Ссылка на документ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Отчётный документ',
                'verbose_name_plural': 'Отчётные документы',
                'db_table': 'work_report',
                'ordering': ['-date_accepted'],
            },
        ),
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='works.worktype', verbose_name='Тип работы'),
        ),
        migrations.CreateModel(
            name='TaskWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=100, verbose_name='Стадия')),
                ('justification', models.CharField(blank=True, max_length=500, verbose_name='Основание')),
                ('executors_list', models.JSONField(blank=True, default=list, verbose_name='Список исполнителей')),
                ('actions', models.JSONField(blank=True, default=dict, verbose_name='Связи с ПП')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_detail', to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Запись плана задач',
                'verbose_name_plural': 'Записи плана задач',
                'db_table': 'work_task_work',
            },
        ),
        migrations.CreateModel(
            name='PPWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_code', models.CharField(blank=True, max_length=50, verbose_name='Код строки')),
                ('work_order', models.CharField(blank=True, max_length=100, verbose_name='Заказ-наряд')),
                ('stage_num', models.CharField(blank=True, max_length=50, verbose_name='Этап')),
                ('milestone_num', models.CharField(blank=True, max_length=50, verbose_name='Подэтап')),
                ('work_num', models.CharField(blank=True, max_length=50, verbose_name='Номер работы')),
                ('work_designation', models.CharField(blank=True, max_length=200, verbose_name='Обозначение')),
                ('sheets_a4', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Листы А4')),
                ('norm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Норма (чел.-ч)')),
                ('coeff', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Коэффициент')),
                ('total_2d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Трудоёмкость 2D')),
                ('total_3d', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Трудоёмкость 3D')),
                ('labor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Трудозатраты итого')),
                ('sector_head_name', models.CharField(blank=True, max_length=200, verbose_name='Начальник сектора')),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pp_detail', to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Запись производственного плана',
                'verbose_name_plural': 'Записи производственного плана',
                'db_table': 'work_pp_work',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_type', models.CharField(blank=True, max_length=100, verbose_name='Тип извещения')),
                ('date_issued', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='Тема')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('closed', 'Закрыто')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='employees.department', verbose_name='Отдел')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='employees.employee', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Извещение',
                'verbose_name_plural': 'Журнал извещений',
                'db_table': 'work_notice',
                'ordering': ['-date_issued'],
            },
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['source_type'], name='work_work_source__da40b2_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['department'], name='work_work_departm_6ff55a_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['executor'], name='work_work_executo_8f265d_idx'),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['date_start', 'date_end'], name='work_work_date_st_6a4e34_idx'),
        ),
        migrations.AddIndex(
            model_name='ppwork',
            index=models.Index(fields=['work_order'], name='work_pp_wor_work_or_1e4ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='ppwork',
            index=models.Index(fields=['row_code'], name='work_pp_wor_row_cod_b4339f_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['status'], name='work_notice_status_c4781b_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['department'], name='work_notice_departm_14fae8_idx'),
        ),
    ]
