# Generated by Django 3.2.25 on 2026-03-07 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("works", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dir_type",
                    models.CharField(
                        choices=[
                            ("center", "НТЦ-центр"),
                            ("position", "Должность"),
                            ("dept", "Отдел"),
                            ("sector", "Сектор"),
                            ("executor", "Исполнитель"),
                            ("task_type", "Тип работы"),
                            ("work_type", "Вид работы"),
                            ("justification", "Обоснование"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("value", models.CharField(max_length=500, verbose_name="Значение")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="works.directory",
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Справочник",
                "verbose_name_plural": "Справочники",
                "db_table": "work_directory",
                "ordering": ["dir_type", "value"],
            },
        ),
        migrations.AddField(
            model_name="ppwork",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_pp_works",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал",
            ),
        ),
        migrations.AddField(
            model_name="ppwork",
            name="task_type",
            field=models.CharField(
                blank=True,
                default="выпуск документа",
                max_length=100,
                verbose_name="Тип работы",
            ),
        ),
        migrations.CreateModel(
            name="TaskExecutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "executor_name",
                    models.CharField(max_length=200, verbose_name="ФИО исполнителя"),
                ),
                (
                    "plan_hours",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Плановые часы (по месяцам)",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_executors",
                        to="works.work",
                        verbose_name="Работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исполнитель задачи",
                "verbose_name_plural": "Исполнители задач",
                "db_table": "work_task_executor",
            },
        ),
        migrations.CreateModel(
            name="PPProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pp_projects",
                        to="works.directory",
                        verbose_name="Связь со справочником",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект ПП",
                "verbose_name_plural": "Проекты ПП",
                "db_table": "work_pp_project",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ppwork",
            name="pp_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pp_works",
                to="works.ppproject",
                verbose_name="Проект ПП",
            ),
        ),
        migrations.AddIndex(
            model_name="taskexecutor",
            index=models.Index(fields=["work"], name="work_task_e_work_id_51c543_idx"),
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(
                fields=["dir_type"], name="work_direct_dir_typ_b078a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(
                fields=["dir_type", "value"], name="work_direct_dir_typ_affeec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(
                fields=["parent"], name="work_direct_parent__b2b646_idx"
            ),
        ),
    ]
