# Generated by Django 4.2.20 on 2026-03-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20260307_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='dir_type',
            field=models.CharField(choices=[('center', 'НТЦ-центр'), ('position', 'Должность'), ('dept', 'Отдел'), ('sector', 'Сектор'), ('executor', 'Исполнитель'), ('task_type', 'Тип работы'), ('work_type', 'Вид работы'), ('justification', 'Обоснование'), ('project', 'Проект'), ('milestone', 'Этап'), ('stage', 'Подэтап'), ('substage', 'Работа')], max_length=20, verbose_name='Тип'),
        ),
    ]
