# Generated by Django 3.2.25 on 2026-03-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0011_auto_20260308_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_number',
        ),
    ]
