# Generated by Django 3.2.25 on 2026-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0012_remove_duplicate_sp_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='dir_type',
            field=models.CharField(choices=[('center', 'НТЦ-центр'), ('position', 'Должность'), ('dept', 'Отдел'), ('sector', 'Сектор'), ('executor', 'Исполнитель'), ('task_type', 'Тип работы'), ('work_type', 'Вид работы'), ('justification', 'Обоснование'), ('project', 'Проект'), ('milestone', 'Этап'), ('stage', 'Веха'), ('substage', 'Работа')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='work',
            name='milestone_num',
            field=models.CharField(blank=True, max_length=50, verbose_name='Веха'),
        ),
    ]
