# Generated by Django 3.2.25 on 2026-03-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_ntc_to_department'),
        ('works', '0013_rename_podjetap_to_veha'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='date_expires',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AddField(
            model_name='notice',
            name='group',
            field=models.CharField(blank=True, max_length=200, verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='№ ПИ'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='date_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='employees.employee', verbose_name='Разработчик'),
        ),
    ]
