# Generated by Django 3.2.25 on 2026-03-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_add_ntc_to_department"),
        ("works", "0014_add_notice_number_group_expires"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notices",
                to="employees.sector",
                verbose_name="Сектор",
            ),
        ),
    ]
