# Generated by Django 3.2.25 on 2026-03-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0015_add_notice_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='doc_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Номер (для корректировки)'),
        ),
    ]
