# Generated by Django 3.2.25 on 2026-03-09 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0016_add_workreport_doc_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="coeff",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Коэффициент",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="labor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Трудозатраты итого",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="norm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Норма (чел.-ч)",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="sheets_a4",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Листы А4",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="total_2d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Трудоёмкость 2D",
            ),
        ),
        migrations.AlterField(
            model_name="work",
            name="total_3d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Трудоёмкость 3D",
            ),
        ),
    ]
