# Generated by Django 3.2.25 on 2026-03-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0018_add_workreport_ii_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='date_expires',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='date_accepted',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
    ]
