# Generated by Django 3.2.25 on 2026-03-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0019_add_workreport_date_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='doc_designation',
            field=models.CharField(blank=True, max_length=200, verbose_name='Обозначение'),
        ),
        migrations.AddField(
            model_name='notice',
            name='ii_pi',
            field=models.CharField(blank=True, max_length=10, verbose_name='ИИ/ПИ'),
        ),
    ]
