# Generated by Django 3.2.25 on 2026-03-10 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0023_add_validators_and_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='closure_date_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Дата документа погашения'),
        ),
        migrations.AddField(
            model_name='notice',
            name='closure_executor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Исполнитель погашения'),
        ),
        migrations.AddField(
            model_name='notice',
            name='closure_notice_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='№ документа погашения'),
        ),
        migrations.AddField(
            model_name='notice',
            name='work_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice', to='works.workreport', verbose_name='Отчётный документ'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='dir_type',
            field=models.CharField(choices=[('center', 'НТЦ-центр'), ('position', 'Должность'), ('dept', 'Отдел'), ('sector', 'Сектор'), ('executor', 'Исполнитель'), ('task_type', 'Тип работы'), ('justification', 'Обоснование'), ('project', 'Проект'), ('milestone', 'Этап'), ('stage', 'Веха'), ('substage', 'Работа')], max_length=20, verbose_name='Тип'),
        ),
    ]
