# Generated by Django 3.2.25 on 2026-03-11 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_add_ntc_to_department'),
        ('works', '0025_alter_notice_status_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='executor_name_raw',
        ),
        migrations.RemoveField(
            model_name='work',
            name='sector_head_name',
        ),
        migrations.AddField(
            model_name='taskexecutor',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executor_entries', to='employees.employee', verbose_name='Исполнитель'),
        ),
    ]
