# Generated by Django 3.2.25 on 2026-03-12 03:32

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0026_remove_executor_name_raw_sector_head_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('task_create', 'Создание задачи'), ('task_update', 'Изменение задачи'), ('task_delete', 'Удаление задачи'), ('pp_sync', 'Синхронизация ПП'), ('pp_create', 'Создание записи ПП'), ('pp_delete', 'Удаление записи ПП'), ('role_change', 'Смена роли пользователя'), ('user_create', 'Создание пользователя'), ('user_delete', 'Удаление пользователя'), ('dep_create', 'Создание зависимости'), ('dep_update', 'Изменение зависимости'), ('dep_delete', 'Удаление зависимости'), ('dep_align', 'Выравнивание дат')], max_length=30, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_type', models.CharField(choices=[('FS', 'Окончание–Начало (FS)'), ('SS', 'Начало–Начало (SS)'), ('FF', 'Окончание–Окончание (FF)'), ('SF', 'Начало–Окончание (SF)')], default='FS', max_length=2, verbose_name='Тип связи')),
                ('lag_days', models.IntegerField(default=0, verbose_name='Лаг (дней)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successor_links', to='works.work', verbose_name='Предшественник')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessor_links', to='works.work', verbose_name='Последователь')),
            ],
            options={
                'verbose_name': 'Зависимость задач',
                'verbose_name_plural': 'Зависимости задач',
                'db_table': 'work_task_dependency',
            },
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['predecessor'], name='work_task_d_predece_0686bd_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['successor'], name='work_task_d_success_ef9328_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(check=models.Q(('predecessor', django.db.models.expressions.F('successor')), _negated=True), name='dep_no_self_link'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('predecessor', 'successor')},
        ),
    ]
