# Generated by Django 3.2.25 on 2026-03-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0029_add_holiday_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="row_code_seq",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счётчик row_code"
            ),
        ),
    ]
