# Generated by Django 3.2.25 on 2026-03-23 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0034_modernize_unique_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('functionality', 'Функционал'), ('logic', 'Логика / Алгоритмы'), ('design', 'Оформление'), ('bug', 'Ошибка'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('accepted', 'Принято'), ('implemented', 'Выполнено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, default='', verbose_name='Комментарий администратора')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='feedback/', verbose_name='Скриншот')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Замечание / Предложение',
                'verbose_name_plural': 'Замечания и предложения',
                'db_table': 'work_feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
