# Generated by Django 3.2.25 on 2026-03-23 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0035_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="feedback/", verbose_name="Изображение"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="works.feedback",
                    ),
                ),
            ],
            options={
                "db_table": "work_feedback_attachment",
                "ordering": ["created_at"],
            },
        ),
    ]
