# Generated by Django 3.2.25 on 2026-03-26 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0014_clear_more_self_registered'),
        ('works', '0036_feedback_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changeset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('review', 'На согласовании'), ('approved', 'Утверждён'), ('rejected', 'Отклонён')], default='draft', max_length=20, verbose_name='Статус')),
                ('reject_comment', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рецензии')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата применения')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_changesets', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changesets', to='employees.department', verbose_name='Подразделение')),
                ('pp_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changesets', to='works.ppproject', verbose_name='Проект ПП')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changesets', to=settings.AUTH_USER_MODEL, verbose_name='Рецензент')),
            ],
            options={
                'verbose_name': 'Набор изменений',
                'verbose_name_plural': 'Наборы изменений',
                'db_table': 'work_changeset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('task_create', 'Создание задачи'), ('task_update', 'Изменение задачи'), ('task_delete', 'Удаление задачи'), ('pp_sync', 'Синхронизация ПП'), ('pp_create', 'Создание записи ПП'), ('pp_update', 'Изменение записи ПП'), ('pp_delete', 'Удаление записи ПП'), ('role_change', 'Смена роли пользователя'), ('user_create', 'Создание пользователя'), ('user_delete', 'Удаление пользователя'), ('dep_create', 'Создание зависимости'), ('dep_update', 'Изменение зависимости'), ('dep_delete', 'Удаление зависимости'), ('dep_align', 'Выравнивание дат'), ('cs_create', 'Создание набора изменений'), ('cs_submit', 'Отправка на согласование'), ('cs_approve', 'Утверждение набора изменений'), ('cs_reject', 'Отклонение набора изменений')], max_length=30, verbose_name='Действие'),
        ),
        migrations.CreateModel(
            name='ChangesetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление')], max_length=10, verbose_name='Действие')),
                ('field_changes', models.JSONField(blank=True, default=dict, help_text='Для create: все поля новой строки. Для update: только изменённые поля.', verbose_name='Изменения полей')),
                ('original_data', models.JSONField(blank=True, default=dict, help_text='Снимок оригинальных значений для обнаружения конфликтов.', verbose_name='Исходные данные')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('changeset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='works.changeset', verbose_name='Набор изменений')),
                ('target_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changeset_items', to='works.work', verbose_name='Строка ПП')),
            ],
            options={
                'verbose_name': 'Элемент набора изменений',
                'verbose_name_plural': 'Элементы набора изменений',
                'db_table': 'work_changeset_item',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='changesetitem',
            index=models.Index(fields=['changeset'], name='work_change_changes_4cecd3_idx'),
        ),
        migrations.AddIndex(
            model_name='changesetitem',
            index=models.Index(fields=['target_row'], name='work_change_target__af9560_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['status'], name='work_change_status_2e6303_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['department'], name='work_change_departm_d5e8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='changeset',
            index=models.Index(fields=['pp_project'], name='work_change_pp_proj_865a40_idx'),
        ),
    ]
