# Generated by Django 3.2.25 on 2026-03-26 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0037_changeset_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='works.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Комментарий к работе',
                'verbose_name_plural': 'Комментарии к работам',
                'db_table': 'work_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workcomment',
            index=models.Index(fields=['work'], name='work_commen_work_id_ad01a4_idx'),
        ),
    ]
