# Generated by Django 3.2.25 on 2026-03-28 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('employees', '0016_enterprise_roles_staff_count'),
        ('works', '0041_add_date_end_plan_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chief_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_designer_projects', to='employees.employee', verbose_name='Главный конструктор'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority_category',
            field=models.CharField(blank=True, choices=[('critical', 'Критический'), ('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=10, null=True, verbose_name='Категория приоритета'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Числовой приоритет'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('prospective', 'Перспективный'), ('approved', 'Одобренный'), ('active', 'Действующий'), ('suspended', 'Приостановленный'), ('deferred', 'Отложенный'), ('closed', 'Закрытый'), ('cancelled', 'Отменённый')], default='active', max_length=20, verbose_name='Статус проекта'),
        ),
        migrations.AddField(
            model_name='work',
            name='cross_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='enterprise.crossstage', verbose_name='Этап сквозного графика'),
        ),
    ]
