# Generated by Django 3.2.25 on 2026-04-01 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0043_add_report_and_taskexec_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("task_create", "Создание задачи"),
                    ("task_update", "Изменение задачи"),
                    ("task_delete", "Удаление задачи"),
                    ("pp_sync", "Синхронизация ПП"),
                    ("pp_create", "Создание записи ПП"),
                    ("pp_update", "Изменение записи ПП"),
                    ("pp_delete", "Удаление записи ПП"),
                    ("role_change", "Смена роли пользователя"),
                    ("user_create", "Создание пользователя"),
                    ("user_delete", "Удаление пользователя"),
                    ("dep_create", "Создание зависимости"),
                    ("dep_update", "Изменение зависимости"),
                    ("dep_delete", "Удаление зависимости"),
                    ("dep_align", "Выравнивание дат"),
                    ("cs_create", "Создание набора изменений"),
                    ("cs_submit", "Отправка на согласование"),
                    ("cs_approve", "Утверждение набора изменений"),
                    ("cs_reject", "Отклонение набора изменений"),
                    ("comment_delete", "Удаление комментария"),
                ],
                max_length=30,
                verbose_name="Действие",
            ),
        ),
        migrations.CreateModel(
            name="PPStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Наименование этапа"),
                ),
                (
                    "stage_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Номер этапа",
                    ),
                ),
                (
                    "work_order",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Наряд-заказ",
                    ),
                ),
                (
                    "row_code",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Код строки"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "pp_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="works.ppproject",
                        verbose_name="Проект ПП",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап ПП",
                "verbose_name_plural": "Этапы ПП",
                "db_table": "work_pp_stage",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="work",
            name="pp_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="works",
                to="works.ppstage",
                verbose_name="Этап ПП",
            ),
        ),
    ]
