# Generated by Django 3.2.25 on 2026-04-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0045_ppstage_to_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="row_code_seq",
        ),
    ]
