# Generated by Django 3.2.25 on 2026-04-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0047_work_num_seq'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='pp_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание (ПП)'),
        ),
        migrations.AddField(
            model_name='work',
            name='pp_date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало (ПП)'),
        ),
    ]
