# Generated by Django 3.2.25 on 2026-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0048_pp_date_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Виден только администраторам",
                verbose_name="Скрытый проект",
            ),
        ),
    ]
