# Generated by Django 3.2.25 on 2026-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("works", "0049_project_is_hidden"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notif_user_read_created",
            ),
        ),
    ]
