# Generated by Django 3.2.25 on 2026-03-28 00:50

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("works", "0041_add_date_end_plan_index"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("employees", "0016_enterprise_roles_staff_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Номер итерации"),
                ),
                (
                    "edit_owner",
                    models.CharField(
                        choices=[
                            ("cross", "Сквозной график"),
                            ("pp", "Производственные планы"),
                            ("locked", "Заблокирован (финал)"),
                        ],
                        default="cross",
                        max_length=10,
                        verbose_name="Владелец редактирования",
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("whole", "Весь график"),
                            ("per_dept", "По подразделениям"),
                        ],
                        default="whole",
                        max_length=10,
                        verbose_name="Гранулярность блокировки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                        verbose_name="Создал",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cross_schedule",
                        to="works.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сквозной график",
                "verbose_name_plural": "Сквозные графики",
                "db_table": "ent_cross_schedule",
            },
        ),
        migrations.CreateModel(
            name="GeneralSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                        verbose_name="Создал",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_schedule",
                        to="works.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Генеральный график",
                "verbose_name_plural": "Генеральные графики",
                "db_table": "ent_general_schedule",
            },
        ),
        migrations.CreateModel(
            name="GGStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "labor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Трудозатраты (ч/ч)",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "parent_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_stages",
                        to="enterprise.ggstage",
                        verbose_name="Родительская стадия",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="enterprise.generalschedule",
                        verbose_name="ГГ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стадия ГГ",
                "verbose_name_plural": "Стадии ГГ",
                "db_table": "ent_gg_stage",
                "ordering": ["schedule", "order"],
            },
        ),
        migrations.CreateModel(
            name="GGTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название шаблона"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                        verbose_name="Создал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон ГГ",
                "verbose_name_plural": "Шаблоны ГГ",
                "db_table": "ent_gg_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Активный"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                        verbose_name="Создал",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scenarios",
                        to="works.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сценарий What-If",
                "verbose_name_plural": "Сценарии What-If",
                "db_table": "ent_scenario",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Данные")),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="enterprise.scenario",
                        verbose_name="Сценарий",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="works.work",
                        verbose_name="Оригинал работы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись сценария",
                "verbose_name_plural": "Записи сценариев",
                "db_table": "ent_scenario_entry",
            },
        ),
        migrations.CreateModel(
            name="GGTemplateStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=300, verbose_name="Название стадии"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="enterprise.ggtemplate",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стадия шаблона ГГ",
                "verbose_name_plural": "Стадии шаблона ГГ",
                "db_table": "ent_gg_template_stage",
                "ordering": ["template", "order"],
            },
        ),
        migrations.CreateModel(
            name="GGStageDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dep_type",
                    models.CharField(
                        choices=[
                            ("FS", "Финиш-Старт"),
                            ("SS", "Старт-Старт"),
                            ("FF", "Финиш-Финиш"),
                            ("SF", "Старт-Финиш"),
                        ],
                        default="FS",
                        max_length=2,
                        verbose_name="Тип связи",
                    ),
                ),
                (
                    "lag_days",
                    models.IntegerField(default=0, verbose_name="Задержка (дней)"),
                ),
                (
                    "predecessor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successor_deps",
                        to="enterprise.ggstage",
                        verbose_name="Предшественник",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predecessor_deps",
                        to="enterprise.ggstage",
                        verbose_name="Последователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Связь стадий ГГ",
                "verbose_name_plural": "Связи стадий ГГ",
                "db_table": "ent_gg_stage_dependency",
            },
        ),
        migrations.CreateModel(
            name="GGMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="enterprise.generalschedule",
                        verbose_name="ГГ",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones",
                        to="enterprise.ggstage",
                        verbose_name="Привязка к стадии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Веха ГГ",
                "verbose_name_plural": "Вехи ГГ",
                "db_table": "ent_gg_milestone",
            },
        ),
        migrations.CreateModel(
            name="EnterpriseNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reallocation_request", "Запрос на перераспределение"),
                            ("reallocation_result", "Результат согласования"),
                            ("phase_change", "Смена фазы"),
                            ("priority_confirm", "Подтверждение приоритетов"),
                        ],
                        max_length=30,
                        verbose_name="Тип",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("message", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "related_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID объекта"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_notifications",
                        to="employees.employee",
                        verbose_name="Получатель",
                    ),
                ),
                (
                    "related_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Тип объекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "db_table": "ent_notification",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrossStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "cross_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="enterprise.crossschedule",
                        verbose_name="Сквозной график",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.department",
                        verbose_name="Подразделение",
                    ),
                ),
                (
                    "gg_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cross_stages",
                        to="enterprise.ggstage",
                        verbose_name="Стадия ГГ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Этап сквозного графика",
                "verbose_name_plural": "Этапы сквозного графика",
                "db_table": "ent_cross_stage",
                "ordering": ["cross_schedule", "order"],
            },
        ),
        migrations.CreateModel(
            name="CrossScheduleDeptStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Передано"),
                            ("in_progress", "В работе"),
                            ("returned", "Возвращено"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "cross_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dept_statuses",
                        to="enterprise.crossschedule",
                        verbose_name="Сквозной график",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.department",
                        verbose_name="Подразделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статус подразделения",
                "verbose_name_plural": "Статусы подразделений",
                "db_table": "ent_cross_dept_status",
            },
        ),
        migrations.CreateModel(
            name="CrossMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Название")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "cross_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="enterprise.crossschedule",
                        verbose_name="Сквозной график",
                    ),
                ),
                (
                    "cross_stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="milestones",
                        to="enterprise.crossstage",
                        verbose_name="Привязка к этапу",
                    ),
                ),
            ],
            options={
                "verbose_name": "Веха сквозного графика",
                "verbose_name_plural": "Вехи сквозного графика",
                "db_table": "ent_cross_milestone",
            },
        ),
        migrations.CreateModel(
            name="BaselineSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(verbose_name="Номер версии")),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="employees.employee",
                        verbose_name="Создал",
                    ),
                ),
                (
                    "cross_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="enterprise.crossschedule",
                        verbose_name="Сквозной график",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок версии",
                "verbose_name_plural": "Снимки версий",
                "db_table": "ent_baseline_snapshot",
                "ordering": ["cross_schedule", "-version"],
            },
        ),
        migrations.CreateModel(
            name="BaselineEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Данные")),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="enterprise.baselinesnapshot",
                        verbose_name="Снимок",
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="works.work",
                        verbose_name="Работа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись снимка",
                "verbose_name_plural": "Записи снимков",
                "db_table": "ent_baseline_entry",
            },
        ),
        migrations.AddConstraint(
            model_name="ggtemplatestage",
            constraint=models.UniqueConstraint(
                fields=("template", "order"), name="ent_gg_tpl_stage_order_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="ggstagedependency",
            constraint=models.UniqueConstraint(
                fields=("predecessor", "successor"), name="ent_gg_dep_pair_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="ggstagedependency",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("predecessor", django.db.models.expressions.F("successor")),
                    _negated=True,
                ),
                name="ent_gg_dep_no_self_link",
            ),
        ),
        migrations.AddIndex(
            model_name="ggstage",
            index=models.Index(
                fields=["schedule", "order"], name="ent_gg_stage_sch_ord_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ggstage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_start__isnull", True),
                    ("date_end__isnull", True),
                    ("date_end__gte", django.db.models.expressions.F("date_start")),
                    _connector="OR",
                ),
                name="ent_gg_stage_dates_check",
            ),
        ),
        migrations.AddIndex(
            model_name="enterprisenotification",
            index=models.Index(
                fields=["recipient", "is_read", "created_at"],
                name="ent_notif_recipient_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crossstage",
            index=models.Index(
                fields=["cross_schedule", "order"], name="ent_cross_stage_sch_ord_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crossstage",
            index=models.Index(fields=["department"], name="ent_cross_stage_dept_idx"),
        ),
        migrations.AddIndex(
            model_name="crossstage",
            index=models.Index(fields=["gg_stage"], name="ent_cross_stage_gg_idx"),
        ),
        migrations.AddConstraint(
            model_name="crossscheduledeptstatus",
            constraint=models.UniqueConstraint(
                fields=("cross_schedule", "department"),
                name="ent_cross_dept_status_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="baselinesnapshot",
            constraint=models.UniqueConstraint(
                fields=("cross_schedule", "version"), name="ent_baseline_sch_ver_uniq"
            ),
        ),
    ]
