# Generated by Django 3.2.25 on 2026-03-29 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="crossstage",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_stages",
                to="enterprise.crossstage",
                verbose_name="Родительский пункт",
            ),
        ),
        migrations.AlterField(
            model_name="crossstage",
            name="gg_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cross_stages",
                to="enterprise.ggstage",
                verbose_name="Пункт ГГ",
            ),
        ),
    ]
