# Generated by Django 5.2.13 on 2026-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0002_cross_stage_parent_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprisenotification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reallocation_request", "Запрос на перераспределение"),
                    ("reallocation_result", "Результат согласования"),
                    ("phase_change", "Смена фазы"),
                    ("priority_confirm", "Подтверждение приоритетов"),
                    ("delegation_reminder", "Напоминание о делегировании"),
                ],
                max_length=30,
                verbose_name="Тип",
            ),
        ),
    ]
