# Generated by Django 3.2.25 on 2026-03-06 20:59

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код отдела"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
                "db_table": "emp_department",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Отчество"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("ntc_head", "Руководитель НТЦ"),
                            ("ntc_deputy", "Зам. руководителя НТЦ"),
                            ("dept_head", "Начальник отдела"),
                            ("dept_deputy", "Зам. начальника отдела"),
                            ("sector_head", "Начальник сектора"),
                            ("user", "Исполнитель"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tech_3", "Техник-конструктор"),
                            ("tech_2", "Техник-конструктор 2 кат."),
                            ("tech_1", "Техник-конструктор 1 кат."),
                            ("spec", "Специалист"),
                            ("spec_2", "Специалист 2 кат."),
                            ("spec_1", "Специалист 1 кат."),
                            ("eng_3", "Инженер-конструктор 3 кат."),
                            ("eng_2", "Инженер-конструктор 2 кат."),
                            ("eng_1", "Инженер-конструктор 1 кат."),
                            ("lead_eng", "Ведущий инженер-конструктор"),
                            ("sector_head", "Начальник сектора"),
                            ("dept_deputy", "Зам. начальника отдела"),
                            ("dept_head", "Начальник отдела"),
                            ("dir_direction", "Руководитель направления"),
                            ("ntc_deputy", "Зам. руководителя НТЦ"),
                            ("ntc_head", "Руководитель НТЦ"),
                        ],
                        max_length=30,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
                ),
                (
                    "email_corp",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Корп. email"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата приёма"),
                ),
                (
                    "dismissal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
                (
                    "monthly_hours_norm",
                    models.PositiveSmallIntegerField(
                        default=168, verbose_name="Норма часов/мес"
                    ),
                ),
                (
                    "personal_coeff",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Личный коэффициент",
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False, verbose_name="Сменить пароль при входе"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "col_settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Настройки колонок"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="employees.department",
                        verbose_name="Отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "db_table": "emp_employee",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="NTCCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Код НТЦ"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
            ],
            options={
                "verbose_name": "НТЦ-центр",
                "verbose_name_plural": "НТЦ-центры",
                "db_table": "emp_ntc_center",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Vacation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vac_type",
                    models.CharField(
                        choices=[
                            ("annual", "Ежегодный оплачиваемый"),
                            ("unpaid", "За свой счёт"),
                            ("sick", "Больничный"),
                            ("other", "Иное"),
                        ],
                        default="annual",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Начало")),
                ("date_end", models.DateField(verbose_name="Конец")),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacations",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отпуск",
                "verbose_name_plural": "Отпуска",
                "db_table": "emp_vacation",
                "ordering": ["date_start"],
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, verbose_name="Код сектора")),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="employees.department",
                        verbose_name="Отдел",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сектор",
                "verbose_name_plural": "Секторы",
                "db_table": "emp_sector",
                "ordering": ["department", "code"],
                "unique_together": {("department", "code")},
            },
        ),
        migrations.CreateModel(
            name="RoleDelegation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("center", "НТЦ-центр"),
                            ("dept", "Отдел"),
                            ("sector", "Сектор"),
                            ("executor", "Исполнитель"),
                        ],
                        max_length=10,
                        verbose_name="Тип зоны",
                    ),
                ),
                (
                    "scope_value",
                    models.CharField(max_length=100, verbose_name="Значение"),
                ),
                (
                    "can_write",
                    models.BooleanField(default=False, verbose_name="Право записи"),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Действует до")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "delegate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_received",
                        to="employees.employee",
                        verbose_name="Получает",
                    ),
                ),
                (
                    "delegator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegations_given",
                        to="employees.employee",
                        verbose_name="Делегирует",
                    ),
                ),
            ],
            options={
                "verbose_name": "Делегирование прав",
                "verbose_name_plural": "Делегирования прав",
                "db_table": "emp_role_delegation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год")),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Месяц",
                    ),
                ),
                (
                    "plan_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="Плановые часы",
                    ),
                ),
                (
                    "fact_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=7,
                        verbose_name="Фактические часы",
                    ),
                ),
                (
                    "completion_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Выполнение плана, %",
                    ),
                ),
                (
                    "norm_control_remarks",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Замечания нормоконтроля"
                    ),
                ),
                (
                    "docs_issued",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Выпущено документов"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Итоговый балл KPI",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI",
                "verbose_name_plural": "KPI",
                "db_table": "emp_kpi",
                "ordering": ["-year", "-month", "employee"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("characteristic", "Характеристика"),
                            ("order", "Приказ"),
                            ("certificate", "Удостоверение / сертификат"),
                            ("other", "Прочее"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Тип документа",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата документа"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Содержание / примечания"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="employees.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ сотрудника",
                "verbose_name_plural": "Документы сотрудников",
                "db_table": "emp_document",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="ntc_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="employees.ntccenter",
                verbose_name="НТЦ-центр",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="employees.sector",
                verbose_name="Сектор",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Учётная запись",
            ),
        ),
        migrations.AddConstraint(
            model_name="roledelegation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("delegator", django.db.models.expressions.F("delegate")),
                    _negated=True,
                ),
                name="chk_delegation_not_self",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kpi",
            unique_together={("employee", "year", "month")},
        ),
    ]
