# Generated by Django 4.2.20 on 2026-03-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tech_3", "Техник-конструктор"),
                    ("tech_2", "Техник-конструктор 2 кат."),
                    ("tech_1", "Техник-конструктор 1 кат."),
                    ("spec", "Специалист"),
                    ("spec_2", "Специалист 2 кат."),
                    ("spec_1", "Специалист 1 кат."),
                    ("eng", "Инженер-конструктор"),
                    ("eng_3", "Инженер-конструктор 3 кат."),
                    ("eng_2", "Инженер-конструктор 2 кат."),
                    ("eng_1", "Инженер-конструктор 1 кат."),
                    ("lead_eng", "Ведущий инженер-конструктор"),
                    ("sector_head", "Начальник сектора"),
                    (
                        "dept_deputy_sector",
                        "Зам. начальника отдела – начальник сектора",
                    ),
                    ("dept_deputy", "Зам. начальника отдела"),
                    ("dept_head", "Начальник отдела"),
                    ("dir_direction", "Руководитель направления"),
                    ("ntc_deputy", "Зам. руководителя НТЦ"),
                    ("ntc_head", "Руководитель НТЦ"),
                ],
                max_length=30,
                verbose_name="Должность",
            ),
        ),
    ]
