# Generated by Django 4.2.20 on 2026-03-07 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_add_position_choices"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["ntc_center", "code"],
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="ntc_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="employees.ntccenter",
                verbose_name="НТЦ-центр",
            ),
        ),
    ]
