# Generated by Django 3.2.25 on 2026-03-15 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_add_performance_indexes_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=300, verbose_name='Место назначения')),
                ('purpose', models.CharField(blank=True, max_length=500, verbose_name='Цель командировки')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('plan', 'Запланирована'), ('active', 'В процессе'), ('done', 'Завершена'), ('cancel', 'Отменена')], default='plan', max_length=10, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_trips', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Командировка',
                'verbose_name_plural': 'Командировки',
                'db_table': 'emp_business_trip',
                'ordering': ['date_start'],
            },
        ),
        migrations.AddIndex(
            model_name='businesstrip',
            index=models.Index(fields=['employee', 'date_start'], name='emp_busines_employe_76019b_idx'),
        ),
    ]
