# Generated by Django 3.2.25 on 2026-03-27 19:56

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_clear_more_self_registered'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='businesstrip',
            constraint=models.CheckConstraint(check=models.Q(('date_end__gte', django.db.models.expressions.F('date_start'))), name='trip_date_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='vacation',
            constraint=models.CheckConstraint(check=models.Q(('date_end__gte', django.db.models.expressions.F('date_start'))), name='vacation_date_end_gte_start'),
        ),
    ]
