# Generated by Django 5.2.13 on 2026-04-12 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0016_enterprise_roles_staff_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="roledelegation",
            name="source_vacation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auto_delegations",
                to="employees.vacation",
                verbose_name="Источник (отпуск)",
            ),
        ),
    ]
